// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"encoding/json"
)

type Recipe struct {
	ID          int64
	Name        string
	Ingredients json.RawMessage
	Cost        int32
}
