// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recipe.sql

package models

import (
	"context"
	"encoding/json"
)

const createRecipe = `-- name: CreateRecipe :one
INSERT INTO recipe (
    name, ingredients, cost
) VALUES (
    $1, $2, $3
) RETURNING id, name, ingredients, cost
`

type CreateRecipeParams struct {
	Name        string
	Ingredients json.RawMessage
	Cost        int32
}

func (q *Queries) CreateRecipe(ctx context.Context, arg CreateRecipeParams) (Recipe, error) {
	row := q.db.QueryRow(ctx, createRecipe, arg.Name, arg.Ingredients, arg.Cost)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ingredients,
		&i.Cost,
	)
	return i, err
}

const deleteRecipe = `-- name: DeleteRecipe :exec
DELETE FROM recipe
WHERE id = $1
`

func (q *Queries) DeleteRecipe(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteRecipe, id)
	return err
}

const getRecipe = `-- name: GetRecipe :one
SELECT id, name, ingredients, cost FROM recipe
WHERE id = $1
`

func (q *Queries) GetRecipe(ctx context.Context, id int64) (Recipe, error) {
	row := q.db.QueryRow(ctx, getRecipe, id)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ingredients,
		&i.Cost,
	)
	return i, err
}

const listRecipe = `-- name: ListRecipe :many
SELECT id, name, ingredients, cost
FROM recipe
LIMIT $1 OFFSET $2
`

type ListRecipeParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListRecipe(ctx context.Context, arg ListRecipeParams) ([]Recipe, error) {
	rows, err := q.db.Query(ctx, listRecipe, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipe
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Ingredients,
			&i.Cost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecipe = `-- name: UpdateRecipe :one
UPDATE recipe
SET name = $2,
    ingredients = $3,
    cost = $4
WHERE id = $1
RETURNING id, name, ingredients, cost
`

type UpdateRecipeParams struct {
	ID          int64
	Name        string
	Ingredients json.RawMessage
	Cost        int32
}

func (q *Queries) UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) (Recipe, error) {
	row := q.db.QueryRow(ctx, updateRecipe,
		arg.ID,
		arg.Name,
		arg.Ingredients,
		arg.Cost,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ingredients,
		&i.Cost,
	)
	return i, err
}
